/*
 * Fundamentals: ball control, first touch and passing technique.
 * Same diagram format as drills.js and drills-extra.js.
 */

export const TOUCH_DRILLS = [
  /* ─── Fundamentals ───────────────────────────────────────── */
  {
    id: "wall-passing",
    title: "Wall Passing: Two-Touch to One-Touch",
    category: "fundamentals",
    ages: ["U6-8", "U9-12", "U13-15", "U16+"],
    positions: ["GK", "DEF", "MID", "FWD"],
    format: "Individual",
    players: "1 per wall or rebounder",
    duration: 10,
    intensity: 1,
    area: "Wall + 8 m",
    summary:
      "A wall never gets bored. Pass against a wall or rebounder, cushion the return and set it for the next pass. Hundreds of touches in ten minutes, and a great one for homework.",
    setup: ["One ball per player, 4–6 m from a wall or rebounder.", "Two cones on the floor 2 m apart mark your left and right."],
    steps: [
      "Two-touch: control with one foot, pass with the other. 60 s.",
      "Receive on the right, pass with the left, then the other way round.",
      "One-touch: step back to 3 m and pass first time. 30 s blocks.",
    ],
    points: [
      "First touch goes slightly out of your feet, to the side of the next pass.",
      "Stay on your toes between passes; the return is quick.",
      "Pass with the inside, ankle locked. The ball should come back along the ground.",
    ],
    progressions: [
      "Count passes in 60 s and try to beat your record.",
      "Receive with the sole, then the outside, then the inside.",
      "Laces-driven pass from 8 m, then control it dead.",
    ],
    search: "wall passing drill soccer rebounder first touch",
    diagramName: "Two-touch",
    diagram: {
      field: { type: "grid", w: 10, h: 6, bare: true },
      zones: [{ x: 9.4, y: 0.4, w: 0.4, h: 5.2 }],
      cones: [[3, 2], [3, 4]],
      players: [{ id: "a1", t: "a", x: 3, y: 3, f: 0 }],
      ball: "a1",
      note: "Four to six metres from the wall.",
      frames: [
        { note: "Pass into the wall with the inside of the foot.", ball: [9.2, 3] },
        { note: "Cushion the return out to your right.", ball: "a1", move: { a1: [3.2, 3.8] } },
        { note: "Pass with the other foot.", ball: [9.2, 3.6] },
        { note: "Cushion out to the left. Keep the rhythm.", ball: "a1", move: { a1: [3.2, 2.2] } },
        { note: "Pass again.", ball: [9.2, 2.6] },
      ],
    },
    variations: [
      {
        name: "One-touch",
        summary: "Move in to 3 m and play every return first time, alternating feet.",
        diagram: {
          field: { type: "grid", w: 10, h: 6, bare: true },
          zones: [{ x: 9.4, y: 0.4, w: 0.4, h: 5.2 }],
          players: [{ id: "a1", t: "a", x: 6, y: 3, f: 0 }],
          ball: "a1",
          note: "Closer to the wall. No stopping the ball.",
          frames: [
            { ball: [9.2, 2.6], note: "Right foot." },
            { ball: "a1", move: { a1: [6, 2.7] } },
            { ball: [9.2, 3.4], note: "Left foot, first time." },
            { ball: "a1", move: { a1: [6, 3.3] } },
            { ball: [9.2, 2.6], note: "Stay light on your feet." },
          ],
        },
      },
    ],
  },
  {
    id: "cushion-control-box",
    title: "Cushion Control: Kill It in the Box",
    category: "fundamentals",
    ages: ["U6-8", "U9-12", "U13-15"],
    positions: ["GK", "DEF", "MID", "FWD"],
    format: "Pairs",
    players: "2",
    duration: 10,
    intensity: 1,
    area: "16 × 6 m",
    summary:
      "Each player stands in a small coned box. Your partner fizzes the ball in; you must stop it inside your box with a single soft touch. Teaches the 'give' in the receiving foot.",
    setup: ["Two 2 × 2 m boxes, 10 m apart. One ball per pair."],
    steps: [
      "Pass firmly into your partner's box.",
      "Receiver stops the ball dead inside their box with one touch = 1 point.",
      "Receiver sets and passes back. First pair to 20 points.",
    ],
    points: [
      "Meet the ball with the foot, then pull it back as it arrives, like catching an egg.",
      "Relaxed ankle for cushioning, locked ankle for passing.",
      "Get your body behind the line of the ball.",
    ],
    progressions: [
      "Receive with the sole only, then the outside only.",
      "Increase the distance to 15 m and the pass speed.",
      "Shrink the box to 1 × 1 m.",
    ],
    search: "soccer first touch cushion control drill",
    diagram: {
      field: { type: "grid", w: 16, h: 6, bare: true },
      cones: [[2, 2], [4, 2], [2, 4], [4, 4], [12, 2], [14, 2], [12, 4], [14, 4]],
      players: [
        { id: "a1", t: "a", x: 3, y: 3, f: 0 },
        { id: "a2", t: "a", x: 13, y: 3, f: 180 },
      ],
      ball: "a1",
      note: "A small box each, 10 m apart.",
      frames: [
        { note: "Firm pass into your partner's box.", ball: "a2" },
        { note: "Cushion: the ball dies inside the box. 1 point.", move: { a2: [13.2, 3.1] } },
        { note: "Set and pass back.", ball: "a1" },
        { note: "Soft foot. Don't let it bounce out.", move: { a1: [2.8, 2.9] } },
      ],
    },
  },
  {
    id: "aerial-control-pairs",
    title: "Aerial Control: Throw, Control, Pass",
    category: "fundamentals",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["GK", "DEF", "MID", "FWD"],
    format: "Pairs",
    players: "2",
    duration: 12,
    intensity: 1,
    area: "12 × 6 m",
    summary:
      "The server throws; the receiver brings the ball down with the instep, thigh or chest and passes back along the ground. Teaches players to get their body in line early and take the pace off a dropping ball.",
    setup: ["Pairs 6–8 m apart. Server holds the ball. Swap every 10 throws."],
    steps: [
      "Underarm throw to the feet: cushion with the instep.",
      "Throw to the thigh: cushion down in front of you.",
      "Throw to the chest: lean back slightly, let it drop, then pass back.",
    ],
    points: [
      "Move your feet so you are in line with the ball early.",
      "Withdraw the surface as the ball arrives to kill the pace.",
      "The second touch is always a pass along the ground.",
    ],
    progressions: [
      "Server calls the surface while the ball is in the air.",
      "Control and pass back in two touches without it bouncing.",
      "Volley pass back with the inside of the foot.",
    ],
    search: "aerial ball control drill thigh chest instep soccer",
    diagram: {
      field: { type: "grid", w: 12, h: 6, bare: true },
      players: [
        { id: "a1", t: "a", x: 2, y: 3, f: 0 },
        { id: "a2", t: "a", x: 9, y: 3, f: 180 },
      ],
      ball: "a1",
      note: "Server with the ball in their hands.",
      frames: [
        { note: "Underarm throw to the feet.", ball: "a2", arc: true },
        { note: "Instep cushion, the ball drops dead.", move: { a2: [8.6, 3] } },
        { note: "Pass back along the ground.", ball: "a1" },
        { note: "Throw to the thigh.", ball: "a2", arc: true, move: { a2: [9, 3.5] } },
        { note: "Thigh down, then pass back.", ball: "a1" },
        { note: "Throw to the chest.", ball: "a2", arc: true, move: { a2: [9, 2.6] } },
        { note: "Chest down, second touch a pass.", ball: "a1" },
      ],
    },
  },
  {
    id: "knockout-keep-your-ball",
    title: "Knockout: Keep Your Ball",
    category: "fundamentals",
    ages: ["U6-8", "U9-12"],
    positions: ["DEF", "MID", "FWD"],
    format: "Team",
    players: "6–16",
    duration: 10,
    intensity: 2,
    area: "20 × 20 m",
    summary:
      "Everyone dribbles inside the square, protecting their own ball while trying to knock other players' balls out. Close control, shielding and head-up dribbling in one noisy game.",
    setup: ["A ball each, all inside the square."],
    steps: [
      "Dribble and keep your ball inside the square.",
      "Knock other players' balls out while keeping your own.",
      "If your ball goes out, fetch it and do 10 toe taps before coming back in.",
    ],
    points: [
      "Keep the ball close and your body between it and the nearest player.",
      "Head up: you can't attack or protect what you don't see.",
      "Use the sole to pull the ball away from danger.",
    ],
    progressions: [
      "Last player left in wins (no coming back in).",
      "Weaker foot only.",
      "Coach joins in as a 'shark' without a ball.",
    ],
    search: "knockout soccer game kids shielding dribbling",
    diagram: {
      field: { type: "grid", w: 20, h: 20 },
      players: [
        { id: "a1", t: "a", x: 4, y: 4 },
        { id: "a2", t: "a", x: 15, y: 5 },
        { id: "a3", t: "a", x: 10, y: 10 },
        { id: "a4", t: "a", x: 4, y: 15 },
        { id: "a5", t: "a", x: 16, y: 16 },
      ],
      balls: { b1: "a1", b2: "a2", b3: "a3", b4: "a4", b5: "a5" },
      note: "A ball each inside the square.",
      frames: [
        { note: "Dribble, head up.", move: { a1: [7, 6], a2: [13, 8], a3: [9, 13], a4: [6, 17], a5: [15, 13] } },
        { note: "A1 closes in on a loose touch…", move: { a1: [10.8, 8], a2: [12.5, 8.5], a3: [7, 14], a5: [17, 11] } },
        { note: "…and knocks it out, keeping their own ball.", balls: { b2: [20.8, 6] } },
        { note: "Fetch it, 10 toe taps, back in.", move: { a2: [20.5, 6.5], a1: [8, 6] } },
      ],
    },
  },
  {
    id: "shielding-pairs",
    title: "Shielding: Hold It for Five",
    category: "fundamentals",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["DEF", "MID", "FWD"],
    format: "Pairs",
    players: "2",
    duration: 10,
    intensity: 3,
    area: "6 × 6 m",
    summary:
      "One player keeps the ball for five seconds while their partner tries to touch it. The arrow shows the attacker turning their back as the defender circles. Low, wide and strong.",
    setup: ["Pairs in a small box. Attacker with the ball, defender starting 1 m away."],
    steps: [
      "Defender tries to touch the ball; attacker shields for 5 s.",
      "Keep the ball inside the box.",
      "Five reps, then swap roles.",
    ],
    points: [
      "Side-on, knees bent, arm out to feel the defender.",
      "Ball on the foot furthest from the defender.",
      "Turn with the defender: always keep your body between them and the ball.",
    ],
    progressions: [
      "Extend to 10 s.",
      "After shielding, turn and dribble out of the box to score.",
      "Add a teammate to play a pass to once you've held it.",
    ],
    search: "shielding the ball drill soccer 1v1",
    diagram: {
      field: { type: "grid", w: 6, h: 6 },
      players: [
        { id: "a1", t: "a", x: 3, y: 3, f: -90 },
        { id: "b1", t: "b", x: 3, y: 4.4 },
      ],
      ball: "a1",
      note: "Defender behind. Attacker faces away.",
      frames: [
        { note: "Back to the defender, ball on the far foot.", call: { id: "a1", text: "1" } },
        { note: "Defender circles to the side: turn with them.", move: { b1: [4.4, 3.2], a1: [2.8, 3] }, face: { a1: 180 }, call: { id: "a1", text: "2" } },
        { note: "Stay low and wide.", call: { id: "a1", text: "3" } },
        { note: "They go back the other way: turn again.", move: { b1: [2.6, 4.3], a1: [3.2, 2.8] }, face: { a1: -60 }, call: { id: "a1", text: "4" } },
        { note: "Five seconds. Point!", call: { id: "a1", text: "5!", color: "g" } },
      ],
    },
  },
  {
    id: "dribble-stop-pass",
    title: "Dribble, Stop, Pass",
    category: "fundamentals",
    ages: ["U6-8", "U9-12"],
    positions: ["DEF", "MID", "FWD"],
    format: "Pairs",
    players: "2",
    duration: 10,
    intensity: 1,
    area: "20 × 6 m",
    summary:
      "Dribble to the middle cone, stop the ball dead with the sole, look up and pass to your partner. Three fundamentals in a row: close control, a clean stop and a set pass.",
    setup: ["Partners 16 m apart, a cone halfway between them."],
    steps: [
      "Dribble to the cone with small touches.",
      "Sole on top of the ball to stop it; look up.",
      "Pass to your partner and jog back to your line. Partner repeats.",
    ],
    points: [
      "Touch the ball every step or two on the way.",
      "Stop it next to the cone, not past it.",
      "Look at your partner before you pass.",
    ],
    progressions: [
      "Turn instead of stopping and dribble back.",
      "Pass with the weaker foot.",
      "Race another pair: 10 passes wins.",
    ],
    search: "dribble stop pass drill kids soccer",
    diagram: {
      field: { type: "grid", w: 20, h: 6, bare: true },
      cones: [[10, 3.2]],
      players: [
        { id: "a1", t: "a", x: 2, y: 3 },
        { id: "a2", t: "a", x: 18, y: 3 },
      ],
      ball: "a1",
      note: "A cone halfway.",
      frames: [
        { note: "Small touches up to the cone.", move: { a1: [8.8, 3] } },
        { note: "Sole stop. Look up!", call: { id: "a1", text: "STOP", color: "r" } },
        { note: "Pass to your partner.", ball: "a2" },
        { note: "Jog back. Partner dribbles to the cone.", move: { a1: [2, 3], a2: [11.2, 3] } },
        { note: "Stop, look, pass.", ball: "a1" },
      ],
    },
  },
  {
    id: "dribble-pass-relay",
    title: "Dribble & Pass Relay",
    category: "fundamentals",
    ages: ["U6-8", "U9-12"],
    positions: ["DEF", "MID", "FWD"],
    format: "Team",
    players: "6–12",
    duration: 10,
    intensity: 2,
    area: "16 × 10 m",
    summary:
      "Teams race: dribble round the far cone, then pass back to the next player in your line. The race makes players want to be quick, and the pass back rewards the one who stays accurate.",
    setup: ["Two or three lines of 3–4 players, a cone 12 m in front of each."],
    steps: [
      "First player dribbles round the cone.",
      "Pass back to the next player from the cone; they can't move until the ball arrives.",
      "Sprint back to the end of your line. First team with everyone through wins.",
    ],
    points: [
      "Small touches going round the cone.",
      "The pass back must reach the next player, so it's not about speed alone.",
      "Next player: be ready, on your toes.",
    ],
    progressions: [
      "Dribble with the weaker foot only.",
      "Add a slalom of cones on the way out.",
      "Next player must control with one touch before going.",
    ],
    search: "dribble and pass relay race soccer kids",
    diagram: {
      field: { type: "grid", w: 16, h: 10, bare: true },
      cones: [[13, 3], [13, 7]],
      players: [
        { id: "a1", t: "a", x: 2, y: 3 },
        { id: "a2", t: "a", x: 1, y: 3 },
        { id: "a3", t: "a", x: 0, y: 3 },
        { id: "b1", t: "b", x: 2, y: 7 },
        { id: "b2", t: "b", x: 1, y: 7 },
        { id: "b3", t: "b", x: 0, y: 7 },
      ],
      balls: { x: "a1", y: "b1" },
      note: "Two teams. Cone 12 m out.",
      frames: [
        { note: "Dribble out to the cone.", move: { a1: [12, 2.3], b1: [11, 7.4] } },
        { note: "Round the cone.", move: { a1: [13.2, 4], b1: [12.8, 8] } },
        { note: "Pass back to the next player.", balls: { x: "a2" }, move: { b1: [14, 6.6] } },
        { note: "Sprint back; next player goes.", move: { a1: [-1, 3.8], a2: [6, 3] }, balls: { y: "b2" } },
      ],
    },
  },
  {
    id: "receiving-surfaces",
    title: "Receiving Surfaces: Inside, Outside, Sole",
    category: "fundamentals",
    ages: ["U9-12", "U13-15"],
    positions: ["DEF", "MID", "FWD"],
    format: "Small group",
    players: "5",
    duration: 12,
    intensity: 1,
    area: "16 × 16 m",
    summary:
      "A server in the middle feeds four players and calls the surface as the ball travels. Receivers must control with the called surface and pass back. Builds a full toolbox of first touches.",
    setup: ["Server in the middle, four players 6 m away on each side. Swap the server every 2 minutes."],
    steps: [
      "Server plays to a player and calls INSIDE, OUTSIDE or SOLE.",
      "Receiver controls with that surface, then passes back.",
      "Server turns to the next player.",
    ],
    points: [
      "Inside: soft ankle, meet the ball in front of the body.",
      "Outside: across the body, toe down, move the ball away.",
      "Sole: foot slightly raised, heel down, trap it flat.",
    ],
    progressions: [
      "Add THIGH and CHEST with thrown serves.",
      "Receivers must move 2 m to receive: no standing still.",
      "Call the surface and a direction: 'Outside, left!'",
    ],
    search: "soccer receiving surfaces drill inside outside sole",
    diagram: {
      field: { type: "grid", w: 16, h: 16, bare: true },
      players: [
        { id: "c", t: "c", x: 8, y: 8 },
        { id: "a1", t: "a", x: 8, y: 2 },
        { id: "a2", t: "a", x: 14, y: 8 },
        { id: "a3", t: "a", x: 8, y: 14 },
        { id: "a4", t: "a", x: 2, y: 8 },
      ],
      ball: "c",
      note: "Server in the middle, four receivers.",
      frames: [
        { note: "Pass and call the surface.", ball: "a1", call: { id: "c", text: "INSIDE" } },
        { note: "Inside-foot control, pass back.", ball: "c", move: { a1: [8.5, 2.4] } },
        { note: "Next receiver.", ball: "a2", call: { id: "c", text: "OUTSIDE", color: "y" } },
        { note: "Outside of the foot, moving the ball away.", move: { a2: [14.2, 10] } },
        { ball: "c" },
        { note: "Sole trap.", ball: "a3", call: { id: "c", text: "SOLE", color: "b" } },
        { ball: "c" },
      ],
    },
  },

  /* ─── Ball Mastery ───────────────────────────────────────── */
  {
    id: "juggling-ladder",
    title: "Juggling Ladder",
    category: "ball-mastery",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["GK", "DEF", "MID", "FWD"],
    format: "Individual",
    players: "Any",
    duration: 10,
    intensity: 1,
    area: "5 × 5 m each",
    summary:
      "Five levels from bounce-and-catch to air-only juggling. Hit the target at one level to move up. Juggling trains the fine touch and ankle control that make first touches soft.",
    setup: ["One ball each. Everyone starts at level 1 and moves up at their own pace."],
    steps: [
      "1 · Drop, let it bounce, laces up, catch. 10 in a row.",
      "2 · Drop, touch with the laces, catch. 10 each foot.",
      "3 · Right, left, catch. 10 in a row.",
      "4 · Thigh, foot, thigh, foot. 10 in a row.",
      "5 · Air only, both feet. Personal record.",
    ],
    points: [
      "Toes up, ankle locked: the ball should come straight back up.",
      "Small touches to waist height.",
      "Stay on your toes and move your feet to the ball.",
    ],
    progressions: [
      "Juggle in pairs: two touches each then pass it over.",
      "Juggle while walking across the grid.",
      "Juggle, then flick up and volley to a partner.",
    ],
    search: "juggling progression beginner soccer levels",
    diagram: {
      field: { type: "grid", w: 25, h: 5 },
      lines: [[5, 0, 5, 5], [10, 0, 10, 5], [15, 0, 15, 5], [20, 0, 20, 5]],
      zones: [
        { x: 0, y: 0, w: 5, h: 5, label: "1" },
        { x: 5, y: 0, w: 5, h: 5, label: "2" },
        { x: 10, y: 0, w: 5, h: 5, label: "3" },
        { x: 15, y: 0, w: 5, h: 5, label: "4" },
        { x: 20, y: 0, w: 5, h: 5, label: "5" },
      ],
      players: [{ id: "a1", t: "a", x: 2.5, y: 3.8 }],
      ball: "a1",
      note: "Five levels. Hit the target to move up.",
      frames: [
        { note: "Level 1: bounce, laces, catch.", call: { id: "a1", text: "10 ✓", color: "g" } },
        { note: "Level 2: laces, catch. Each foot.", quiet: true, move: { a1: [7.5, 3.8] }, call: { id: "a1", text: "10 ✓", color: "g" } },
        { note: "Level 3: right, left, catch.", quiet: true, move: { a1: [12.5, 3.8] }, call: { id: "a1", text: "10 ✓", color: "g" } },
        { note: "Level 4: thigh, foot.", quiet: true, move: { a1: [17.5, 3.8] }, call: { id: "a1", text: "10 ✓", color: "g" } },
        { note: "Level 5: air only. Beat your record.", quiet: true, move: { a1: [22.5, 3.8] }, call: { id: "a1", text: "PB?", color: "y" } },
      ],
    },
  },
  {
    id: "lane-moves",
    title: "Lane Moves: Scissors, Step-Over, Roll",
    category: "ball-mastery",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["DEF", "MID", "FWD"],
    format: "Individual",
    players: "4–12",
    duration: 12,
    intensity: 2,
    area: "20 × 12 m",
    summary:
      "Each player has a lane with two cones acting as defenders. Do a move at each cone and explode away after it. The same move every rep until it is automatic, then change.",
    setup: ["Lanes 3 m wide and 20 m long, two cones in each. Players queue at the start of each lane."],
    steps: [
      "Dribble at the first cone and perform the called move.",
      "Accelerate for 3–4 m, then do it again at the second cone.",
      "Sprint out of the end, jog back down the side.",
    ],
    points: [
      "Slow in, fast out: the move only works if you change pace after it.",
      "Do the move one step before the cone, not on top of it.",
      "Drop the shoulder and sell the fake with your body.",
    ],
    progressions: [
      "Coach calls the move as players arrive at the cone.",
      "Replace the second cone with a passive defender.",
      "Combine two moves at one cone: step-over into a roll.",
    ],
    search: "soccer dribbling moves scissors step over drill cones",
    diagram: {
      field: { type: "grid", w: 20, h: 12 },
      lines: [[0, 3, 20, 3], [0, 6, 20, 6], [0, 9, 20, 9]],
      cones: [[7, 1.5], [14, 1.5], [7, 4.5], [14, 4.5], [7, 7.5], [14, 7.5], [7, 10.5], [14, 10.5]],
      players: [
        { id: "a1", t: "a", x: 1, y: 1.5 },
        { id: "a2", t: "a", x: 1, y: 4.5 },
        { id: "a3", t: "a", x: 1, y: 7.5 },
        { id: "a4", t: "a", x: 1, y: 10.5 },
      ],
      balls: { b1: "a1", b2: "a2", b3: "a3", b4: "a4" },
      note: "One lane each, two cones as defenders.",
      frames: [
        { note: "Dribble in at the first cone.", move: { a1: [5.5, 1.5], a2: [5.5, 4.5], a3: [5.5, 7.5], a4: [5.5, 10.5] } },
        { note: "Scissors one way, take it the other, explode.", move: { a1: [9.5, 2.4], a2: [9.5, 5.4], a3: [9.5, 8.4], a4: [9.5, 11.4] } },
        { note: "Settle, approach the second cone.", move: { a1: [12.5, 1.5], a2: [12.5, 4.5], a3: [12.5, 7.5], a4: [12.5, 10.5] } },
        { note: "Move again, the other way this time.", move: { a1: [16, 0.6], a2: [16, 3.6], a3: [16, 6.6], a4: [16, 9.6] } },
        { note: "Sprint out of the lane.", move: { a1: [20, 1.5], a2: [20, 4.5], a3: [20, 7.5], a4: [20, 10.5] } },
      ],
    },
  },
  {
    id: "mirror-dribbling",
    title: "Mirror Dribbling",
    category: "ball-mastery",
    ages: ["U6-8", "U9-12", "U13-15"],
    positions: ["DEF", "MID", "FWD"],
    format: "Pairs",
    players: "2",
    duration: 8,
    intensity: 2,
    area: "16 × 12 m",
    summary:
      "Partners face each other across a line, both with a ball. The leader dribbles, turns and stops; the follower copies. Keeps heads up, because you can't mirror what you can't see.",
    setup: ["A line down the middle of the grid. Partners either side, a ball each."],
    steps: [
      "Leader dribbles side to side, forward, back, stops and turns.",
      "Follower mirrors every move without crossing the line.",
      "Swap leader every 45 s.",
    ],
    points: [
      "Follower: eyes on your partner, feel the ball.",
      "Leader: change speed and direction suddenly.",
      "Stop the ball with the sole so you can change direction fast.",
    ],
    progressions: [
      "Leader adds skill moves the follower must copy.",
      "Follower tries to get to a gate before the leader.",
      "Leader loses a point if the follower keeps up for 30 s.",
    ],
    search: "mirror dribbling drill soccer shadow partner",
    diagram: {
      field: { type: "grid", w: 16, h: 12 },
      lines: [[0, 6, 16, 6]],
      players: [
        { id: "a1", t: "a", x: 8, y: 3.5, n: "L" },
        { id: "a2", t: "a", x: 8, y: 8.5 },
      ],
      balls: { b1: "a1", b2: "a2" },
      note: "Leader (L) and follower either side of a line.",
      frames: [
        { note: "Leader goes left…", move: { a1: [3, 3.5], a2: [3, 8.5] } },
        { note: "…sole stop and back the other way.", move: { a1: [12, 3], a2: [12, 9] } },
        { note: "Towards the line…", move: { a1: [10, 5], a2: [10, 7] } },
        { note: "…and away. Follower copies everything.", move: { a1: [6, 1.5], a2: [6, 10.5] } },
      ],
    },
  },

  /* ─── Passing & Receiving ────────────────────────────────── */
  {
    id: "directional-first-touch",
    title: "Directional First Touch: Pick a Gate",
    category: "passing",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["DEF", "MID", "FWD"],
    format: "Pairs",
    players: "2",
    duration: 12,
    intensity: 2,
    area: "16 × 12 m",
    summary:
      "The server calls a colour as the pass travels, and the receiver's first touch must go through that gate. The first touch is a decision, not a stop: move the ball where you want to go next.",
    setup: ["Server 8 m from the receiver. Two coloured gates behind the receiver at 45°, one each side."],
    steps: [
      "Server passes and calls RED or YELLOW.",
      "Receiver's first touch goes through that gate.",
      "Dribble back to the start and play a pass to the server. 10 reps, then swap.",
    ],
    points: [
      "Open your body before the ball arrives so either gate is possible.",
      "Touch with the foot furthest from the ball to move it across you.",
      "The touch should be firm enough to go 2–3 m, not die at your feet.",
    ],
    progressions: [
      "Call later, when the ball is nearly there.",
      "Add a passive defender who blocks one gate: go the other way.",
      "Receive, go through the gate and pass to a second server beyond it.",
    ],
    search: "directional first touch drill soccer gates",
    diagram: {
      field: { type: "grid", w: 16, h: 12, bare: true },
      cones: [[13, 2, "r"], [14, 3.6, "r"], [13, 10, "y"], [14, 8.4, "y"]],
      players: [
        { id: "a1", t: "a", x: 2, y: 6 },
        { id: "a2", t: "a", x: 10, y: 6, f: 180 },
      ],
      ball: "a1",
      note: "Two gates behind the receiver.",
      frames: [
        { note: "Pass. Call the colour as it travels.", ball: "a2", move: { a2: [9.6, 6] }, face: { a2: 200 }, call: { id: "a1", text: "RED!", color: "r" } },
        { note: "First touch through the red gate.", move: { a2: [14.2, 2.4] }, face: { a2: -40 } },
        { note: "Back to the start, pass to the server.", move: { a2: [10, 6] }, face: { a2: 180 } },
        { ball: "a1" },
        { note: "Next ball: YELLOW.", ball: "a2", move: { a2: [9.6, 6] }, face: { a2: 160 }, call: { id: "a1", text: "YELLOW!", color: "y" } },
        { note: "Across the body into the yellow gate.", move: { a2: [14.2, 9.6] }, face: { a2: 40 } },
      ],
    },
  },
  {
    id: "check-away-check-to",
    title: "Check Away, Check To",
    category: "passing",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["DEF", "MID", "FWD"],
    format: "Small group",
    players: "3",
    duration: 12,
    intensity: 2,
    area: "16 × 10 m",
    summary:
      "Space to receive is created before the ball comes. The receiver takes their marker away with two steps, then checks sharply back to the ball. A defender who follows the first move is always a step late.",
    setup: ["Passer, receiver and a defender marking the receiver. Rotate every 6 reps."],
    steps: [
      "Receiver walks the defender away from the ball.",
      "Sharp check back towards the passer; the pass arrives as they do.",
      "Receiver sets it back first time, then resets.",
    ],
    points: [
      "Slow away, fast back. The change of pace is what creates the space.",
      "Show a hand where you want it.",
      "Passer: play when the receiver checks, not before.",
    ],
    progressions: [
      "Defender goes live and tries to intercept.",
      "Receiver may spin in behind if the defender stays too tight.",
      "Receiver turns and plays to a third player.",
    ],
    search: "check away check to receiving movement soccer drill",
    diagramName: "Check to",
    diagram: {
      field: { type: "grid", w: 16, h: 10 },
      players: [
        { id: "a1", t: "a", x: 2, y: 5 },
        { id: "a2", t: "a", x: 11, y: 5 },
        { id: "b1", t: "b", x: 12.4, y: 5 },
      ],
      ball: "a1",
      note: "Receiver marked tight.",
      frames: [
        { note: "Walk the defender away.", move: { a2: [13.5, 2.5], b1: [14.4, 3.6] } },
        { note: "Sharp check back to the ball.", move: { a2: [9.5, 4.2], b1: [12, 4] } },
        { note: "Pass arrives as you arrive.", ball: "a2" },
        { note: "Set first time.", ball: "a1" },
      ],
    },
    variations: [
      {
        name: "Spin in behind",
        summary: "If the defender follows the check too tightly, spin off their shoulder and receive the ball in behind.",
        diagram: {
          field: { type: "grid", w: 16, h: 10 },
          players: [
            { id: "a1", t: "a", x: 2, y: 5 },
            { id: "a2", t: "a", x: 11, y: 5 },
            { id: "b1", t: "b", x: 12.4, y: 5 },
          ],
          ball: "a1",
          note: "Receiver marked tight.",
          frames: [
            { note: "Check towards the ball…", move: { a2: [8.5, 5], b1: [9.6, 5] } },
            { note: "…defender follows tight. Spin!", move: { a2: [12, 8] } },
            { note: "Ball in behind.", ball: [15, 7.6], move: { b1: [11, 6.2] } },
            { note: "Run onto it.", ball: "a2", move: { a2: [15, 7.6] } },
          ],
        },
      },
    ],
  },
  {
    id: "weak-foot-clinic",
    title: "Weaker-Foot Clinic",
    category: "passing",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["DEF", "MID", "FWD"],
    format: "Pairs",
    players: "2",
    duration: 12,
    intensity: 1,
    area: "20 × 6 m",
    summary:
      "Weaker foot only, and the partner steps back each time five passes arrive accurately. Players rarely practise their weaker foot unless you make them: this makes it a challenge.",
    setup: ["Pairs, start 5 m apart. Cones at 5, 10 and 15 m."],
    steps: [
      "Pass and receive with the weaker foot only.",
      "Five accurate passes in a row: the receiver steps back to the next cone.",
      "A miss sends you back one cone.",
    ],
    points: [
      "Same technique as your strong foot: plant foot, locked ankle, follow through.",
      "Slow it down; accuracy first.",
      "Receive with the weak foot too.",
    ],
    progressions: [
      "Laces-driven passes at 15 m.",
      "Receive with the strong foot, pass with the weak: no extra touches.",
      "One-touch weak-foot passing at 5 m.",
    ],
    search: "weak foot passing drill soccer",
    diagram: {
      field: { type: "grid", w: 20, h: 6, bare: true },
      cones: [[6.5, 1.5], [11.5, 1.5], [16.5, 1.5]],
      players: [
        { id: "a1", t: "a", x: 1.5, y: 3 },
        { id: "a2", t: "a", x: 6.5, y: 3 },
      ],
      ball: "a1",
      note: "Start at 5 m. Weak foot only.",
      frames: [
        { note: "Weak-foot pass.", ball: "a2" },
        { ball: "a1" },
        { note: "Five accurate? Step back.", move: { a2: [11.5, 3] }, call: { id: "a2", text: "5 ✓", color: "g" } },
        { ball: "a2" },
        { ball: "a1" },
        { note: "Five more: back again.", move: { a2: [16.5, 3] }, call: { id: "a2", text: "5 ✓", color: "g" } },
        { ball: "a2" },
      ],
    },
  },
  {
    id: "driven-passes",
    title: "Driven Passes: Laces Through the Ball",
    category: "passing",
    ages: ["U13-15", "U16+"],
    positions: ["DEF", "MID"],
    format: "Pairs",
    players: "2",
    duration: 15,
    intensity: 2,
    area: "32 × 8 m",
    summary:
      "The flat, fast pass used to switch play and break lines. Pairs 25–30 m apart drive the ball through a gate, keeping it below knee height all the way.",
    setup: ["Pairs 25–30 m apart with a 2 m gate halfway."],
    steps: [
      "Take a touch out of your feet at a slight angle.",
      "Drive the ball through the gate with the laces.",
      "Partner controls and drives it back. 10 each foot.",
    ],
    points: [
      "Approach at a slight angle; plant foot beside the ball.",
      "Strike through the middle of the ball with the laces, toe down.",
      "Land on your kicking foot. Chest over the ball keeps it low.",
    ],
    progressions: [
      "Receiver must be moving: pass into space ahead of them.",
      "Two-touch maximum: control and strike.",
      "Diagonal switch between two channels (below).",
    ],
    search: "driven pass technique drill laces soccer",
    diagramName: "Through the gate",
    diagram: {
      field: { type: "grid", w: 32, h: 8, bare: true },
      cones: [[16, 3], [16, 5]],
      players: [
        { id: "a1", t: "a", x: 2, y: 4 },
        { id: "a2", t: "a", x: 30, y: 4 },
      ],
      ball: "a1",
      note: "25–30 m apart, gate in the middle.",
      frames: [
        { note: "Touch out at an angle.", move: { a1: [3.5, 4.8] } },
        { note: "Drive it through the gate, knee height or lower.", ball: "a2" },
        { note: "Control out of the feet…", move: { a2: [28.8, 3.4] } },
        { note: "…and drive it back.", ball: "a1" },
      ],
    },
    variations: [
      {
        name: "Diagonal switch",
        summary: "Two channels 25 m apart. Players move up their channel and switch diagonally into their partner's stride.",
        diagram: {
          field: { type: "grid", w: 30, h: 24 },
          lines: [[5, 0, 5, 24], [25, 0, 25, 24]],
          players: [
            { id: "a1", t: "a", x: 2.5, y: 21 },
            { id: "a2", t: "a", x: 27.5, y: 17 },
          ],
          ball: "a1",
          note: "A channel each.",
          frames: [
            { note: "Drive it diagonally into space ahead of your partner.", ball: [27.5, 12] },
            { note: "Run onto it.", ball: "a2", move: { a2: [27.5, 12] } },
            { note: "Carry it forward.", move: { a2: [27.5, 8] } },
            { note: "Switch back.", ball: [2.5, 4], move: { a1: [2.5, 10] } },
            { ball: "a1", move: { a1: [2.5, 4] } },
          ],
        },
      },
    ],
  },
  {
    id: "lofted-pass-zone",
    title: "Lofted Pass Into the Zone",
    category: "passing",
    ages: ["U13-15", "U16+"],
    positions: ["DEF", "MID", "GK"],
    format: "Pairs",
    players: "2",
    duration: 15,
    intensity: 2,
    area: "34 × 12 m",
    summary:
      "Chip the ball into a 5 × 5 m target zone 25 m away. The partner must control it without leaving the zone. Trains the lofted technique and the receiver's control of a dropping ball.",
    setup: ["Two 5 × 5 m zones, 25 m apart. A player in each."],
    steps: [
      "Lofted pass into your partner's zone.",
      "Partner controls inside the zone = 1 point for each of you.",
      "Partner lofts it back. 10 each foot.",
    ],
    points: [
      "Plant foot a little behind and beside the ball; lean back slightly.",
      "Strike the lower half of the ball with the instep.",
      "Receiver: judge the flight early and get under it.",
    ],
    progressions: [
      "Shrink the zones to 3 × 3 m.",
      "Receiver may only take one touch before passing back.",
      "Add a defender in the middle who can head the ball away.",
    ],
    search: "lofted pass technique drill soccer long ball",
    diagram: {
      field: { type: "grid", w: 34, h: 12, bare: true },
      zones: [
        { x: 2, y: 3.5, w: 5, h: 5 },
        { x: 27, y: 3.5, w: 5, h: 5 },
      ],
      players: [
        { id: "a1", t: "a", x: 4.5, y: 6 },
        { id: "a2", t: "a", x: 29.5, y: 6 },
      ],
      ball: "a1",
      note: "Target zones 25 m apart.",
      frames: [
        { note: "Lean back, strike the lower half.", ball: "a2", arc: true, move: { a2: [29, 5] } },
        { note: "Get under it and cushion inside the zone.", move: { a2: [29.6, 6.2] } },
        { note: "Loft it back.", ball: "a1", arc: true, move: { a1: [5, 7] } },
      ],
    },
  },
  {
    id: "one-two-basics",
    title: "One-Two (Wall Pass) Basics",
    category: "passing",
    ages: ["U9-12", "U13-15"],
    positions: ["DEF", "MID", "FWD"],
    format: "Small group",
    players: "4–6",
    duration: 12,
    intensity: 2,
    area: "20 × 10 m",
    summary:
      "Dribble at a defender, pass to a wall player, run past the defender and receive the return. The simplest combination in football, and the one young players use most.",
    setup: ["A queue at the start, a passive defender (or tall cone) halfway, a wall player beside and ahead of it."],
    steps: [
      "Dribble at the defender.",
      "Pass to the wall player just before you reach the defender.",
      "Sprint past; the wall plays it first time into your path. Rotate: passer → wall → queue.",
    ],
    points: [
      "Commit the defender by dribbling at them first.",
      "Pass and go straight away: no admiring your pass.",
      "Wall player: set it into space in front of the runner, one touch.",
    ],
    progressions: [
      "Defender goes live.",
      "Finish on a mini-goal.",
      "Wall player on the other side: use the weaker foot.",
    ],
    search: "one two wall pass drill soccer beginners",
    diagram: {
      field: { type: "grid", w: 20, h: 10 },
      players: [
        { id: "a1", t: "a", x: 2, y: 6 },
        { id: "a2", t: "a", x: 0.6, y: 6 },
        { id: "a3", t: "a", x: 10, y: 2 },
        { id: "b1", t: "b", x: 11, y: 6 },
      ],
      ball: "a1",
      note: "Passive defender, wall player on the side.",
      frames: [
        { note: "Drive at the defender.", move: { a1: [7.5, 6] } },
        { note: "Pass to the wall…", ball: "a3" },
        { note: "…and sprint past.", move: { a1: [13, 4.5] } },
        { note: "First-time return into the runner's path.", ball: "a1" },
        { note: "Away and finish.", move: { a1: [19, 4.5] } },
        { note: "Rotate: passer to wall, wall to the queue.", reset: true, move: { a1: [10, 2], a3: [0.6, 6], a2: [2, 6] }, ball: "a2" },
      ],
    },
  },
  {
    id: "passing-gates-race",
    title: "Passing Gates Race",
    category: "passing",
    ages: ["U6-8", "U9-12", "U13-15"],
    positions: ["DEF", "MID", "FWD"],
    format: "Pairs",
    players: "4–16",
    duration: 10,
    intensity: 2,
    area: "25 × 20 m",
    summary:
      "Pairs move around the area passing through as many gates as they can in a minute. Constant movement, accurate short passing and scanning for a free gate.",
    setup: ["8–10 gates of two cones 1.5 m apart, scattered. One ball per pair."],
    steps: [
      "Pass through a gate to your partner = 1 point.",
      "You can't use the same gate twice in a row.",
      "Pairs call their score after 60 s.",
    ],
    points: [
      "Receiver: move to the other side of a free gate early.",
      "Passer: look for the gate your partner is lined up with.",
      "Firm passes, so you can get to the next gate quickly.",
    ],
    progressions: [
      "One-touch through the gates.",
      "Add a defender pair who can block a gate by standing in it.",
      "Weaker foot only.",
    ],
    search: "passing through gates game soccer pairs",
    diagram: {
      field: { type: "grid", w: 25, h: 20 },
      cones: [
        [5, 3.5], [5, 5], [13, 2.5], [14.2, 3.5], [20, 7], [20, 8.5],
        [9, 10], [10.2, 11], [16, 13.5], [16, 15], [5, 15.5], [6.3, 16.5],
      ],
      players: [
        { id: "a1", t: "a", x: 2, y: 4.2 },
        { id: "a2", t: "a", x: 8, y: 4.2 },
        { id: "a3", t: "a", x: 18, y: 14.2 },
        { id: "a4", t: "a", x: 14, y: 14.2 },
      ],
      balls: { b1: "a1", b2: "a3" },
      note: "Two pairs, gates scattered.",
      frames: [
        { note: "Through the gate to your partner.", balls: { b1: "a2", b2: "a4" } },
        { note: "Find the next free gate.", move: { a2: [11.5, 1.5], a1: [15.5, 4.5], a4: [8, 9], a3: [11.2, 12] } },
        { note: "Line up and pass through.", balls: { b1: "a1", b2: "a3" } },
        { note: "Keep moving.", move: { a1: [21.5, 6], a2: [18.5, 9.5], a3: [4, 14], a4: [7.4, 18] } },
        { balls: { b1: "a2", b2: "a4" } },
      ],
    },
  },
  {
    id: "four-corner-two-touch",
    title: "Four-Corner Two-Touch",
    category: "passing",
    ages: ["U9-12", "U13-15"],
    positions: ["DEF", "MID", "FWD"],
    format: "Small group",
    players: "4–5",
    duration: 12,
    intensity: 1,
    area: "12 × 12 m",
    summary:
      "Four players on the corners pass round the square in two touches. The first touch must go across the body towards the next corner, so every receiver practises opening up.",
    setup: ["A 10 m square, a player on each corner. One ball."],
    steps: [
      "Pass to the next corner.",
      "Receiver opens up, touches it across the body towards the next corner, and passes.",
      "Coach calls 'switch' to reverse direction.",
    ],
    points: [
      "Open your hips towards where the ball is going next before it arrives.",
      "Receive with the foot furthest from the passer.",
      "Two touches: control, pass. No third touch.",
    ],
    progressions: [
      "Add a second ball on the opposite corner.",
      "Pass and follow to the next corner.",
      "One-touch with the back foot.",
    ],
    search: "square passing drill two touch open body",
    diagram: {
      field: { type: "grid", w: 12, h: 12 },
      players: [
        { id: "a1", t: "a", x: 1.2, y: 1.2, f: 0 },
        { id: "a2", t: "a", x: 10.8, y: 1.2, f: 180 },
        { id: "a3", t: "a", x: 10.8, y: 10.8, f: -90 },
        { id: "a4", t: "a", x: 1.2, y: 10.8, f: -90 },
      ],
      ball: "a1",
      note: "Pass round the square. Watch the receivers open up.",
      frames: [
        { note: "Receiver opens up before the ball arrives.", face: { a2: 135 } },
        { ball: "a2", note: "Pass." },
        { note: "Touch across the body towards the next corner.", move: { a2: [10.8, 2.6] }, face: { a2: 90 } },
        { note: "Next one opens up; pass.", ball: "a3", face: { a3: 225 } },
        { note: "Across the body again.", move: { a3: [9.4, 10.8] }, face: { a3: 180 } },
        { ball: "a4", face: { a4: -45 } },
        { note: "Keep it going.", move: { a4: [1.2, 9.4] }, face: { a4: -90 } },
      ],
    },
  },
  {
    id: "pairs-passing-on-the-move",
    title: "Pairs Passing on the Move",
    category: "passing",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["DEF", "MID", "FWD"],
    format: "Pairs",
    players: "2",
    duration: 10,
    intensity: 2,
    area: "40 × 12 m",
    summary:
      "Pairs travel the length of the pitch side by side, passing ahead into their partner's stride. Passing into space and receiving on the run, instead of standing still.",
    setup: ["Pairs 6–8 m apart at one end of a long channel. One ball per pair."],
    steps: [
      "Pass ahead of your partner, into their path.",
      "Partner takes it in stride, carries it a few metres and passes back ahead.",
      "Jog back down the side and go again.",
    ],
    points: [
      "Pass to where your partner will be, not where they are.",
      "First touch forward, in your stride.",
      "Use the foot furthest from your partner to receive.",
    ],
    progressions: [
      "One-touch while running.",
      "Weaker foot on the way back.",
      "Speed it up: sprint the channel.",
    ],
    search: "passing on the move pairs drill soccer",
    diagram: {
      field: { type: "grid", w: 40, h: 12 },
      players: [
        { id: "a1", t: "a", x: 2, y: 3 },
        { id: "a2", t: "a", x: 2, y: 9 },
      ],
      ball: "a1",
      note: "Side by side, travelling together.",
      frames: [
        { note: "Pass ahead into your partner's path.", ball: [9, 9], move: { a1: [6, 3] } },
        { note: "Run onto it in stride.", ball: "a2", move: { a2: [9, 9] } },
        { note: "Carry it forward.", move: { a2: [14, 9], a1: [13, 3] } },
        { note: "Pass back ahead.", ball: [21, 3], move: { a2: [17, 9] } },
        { ball: "a1", move: { a1: [21, 3] } },
        { note: "Keep going to the end.", ball: [30, 9], move: { a1: [25, 3], a2: [26, 9] } },
        { ball: "a2", move: { a2: [30, 9] } },
      ],
    },
  },
  {
    id: "receive-and-turn",
    title: "Receive & Turn: Four Turns",
    category: "passing",
    ages: ["U9-12", "U13-15", "U16+"],
    positions: ["MID", "FWD", "DEF"],
    format: "Small group",
    players: "2–4 + server",
    duration: 15,
    intensity: 2,
    area: "20 × 10 m",
    summary:
      "The receiver checks to the server with their back to a gate, then turns with a different technique each rep: inside hook, outside hook, Cruyff and the open-body turn. Then drive through the gate.",
    setup: ["Server at one end, a gate at the other. Receiver starts in the middle, back to the gate."],
    steps: [
      "Receiver checks towards the server.",
      "Receive and turn with the called technique.",
      "Dribble through the gate and join the back of the queue.",
    ],
    points: [
      "Look over your shoulder before the ball arrives.",
      "Turn on the first touch whenever you can.",
      "Accelerate for 3 m after the turn.",
    ],
    progressions: [
      "Add a passive defender behind the receiver.",
      "Defender goes live: turn if there's space, set back if not.",
      "Finish on goal instead of through a gate.",
    ],
    search: "receiving and turning drill soccer inside hook cruyff",
    diagramName: "Inside hook",
    diagram: {
      field: { type: "grid", w: 20, h: 10, bare: true },
      cones: [[19, 3.5], [19, 6.5]],
      players: [
        { id: "c", t: "c", x: 2, y: 5 },
        { id: "a1", t: "a", x: 12, y: 5, f: 180 },
      ],
      ball: "c",
      note: "Back to the gate.",
      frames: [
        { note: "Check towards the server.", move: { a1: [9, 5] } },
        { note: "Pass in.", ball: "a1" },
        { note: "Inside hook: cut it back behind you with the inside.", move: { a1: [9.5, 6.4] }, face: { a1: 0 } },
        { note: "Accelerate through the gate.", move: { a1: [19.8, 5] } },
      ],
    },
    variations: [
      {
        name: "Open-body turn",
        summary: "The best turn: open up side-on as the ball arrives and let it run across the body with the back foot.",
        diagram: {
          field: { type: "grid", w: 20, h: 10, bare: true },
          cones: [[19, 3.5], [19, 6.5]],
          players: [
            { id: "c", t: "c", x: 2, y: 5 },
            { id: "a1", t: "a", x: 12, y: 5, f: 180 },
          ],
          ball: "c",
          note: "Back to the gate.",
          frames: [
            { note: "Check, but come in side-on.", move: { a1: [9.5, 4.2] }, face: { a1: 135 } },
            { note: "Pass in.", ball: "a1" },
            { note: "Back foot, across the body: turned in one touch.", move: { a1: [11.8, 4.8] }, face: { a1: 0 } },
            { note: "Through the gate.", move: { a1: [19.8, 5] } },
          ],
        },
      },
      {
        name: "Cruyff",
        summary: "Fake a pass, then drag the ball behind the standing leg with the inside and go the other way.",
        diagram: {
          field: { type: "grid", w: 20, h: 10, bare: true },
          cones: [[19, 3.5], [19, 6.5]],
          players: [
            { id: "c", t: "c", x: 2, y: 5 },
            { id: "a1", t: "a", x: 12, y: 5, f: 180 },
            { id: "b1", t: "b", x: 13.5, y: 5 },
          ],
          ball: "c",
          note: "A passive defender follows the receiver.",
          frames: [
            { note: "Check to the ball, defender follows.", move: { a1: [9, 5], b1: [10.4, 5] } },
            { ball: "a1" },
            { note: "Fake to pass, drag it behind the standing leg.", move: { a1: [9.4, 7] }, face: { a1: 45 } },
            { note: "Away round the defender.", move: { a1: [19.8, 6] } },
          ],
        },
      },
    ],
  },

  /* ─── Possession ─────────────────────────────────────────── */
  {
    id: "rondo-3v1",
    title: "3v1 Triangle Rondo",
    category: "possession",
    ages: ["U9-12", "U13-15"],
    positions: ["DEF", "MID", "FWD"],
    format: "Small group",
    players: "4",
    duration: 10,
    intensity: 2,
    area: "10 × 10 m",
    summary:
      "The first rondo. Three attackers keep the ball from one defender. The lesson: the player without the ball moves to make a triangle, so there are always two passing options.",
    setup: ["Three attackers on the edges of a 10 m square, one defender inside."],
    steps: [
      "Attackers keep the ball, two touches.",
      "Attackers move along the edges so the defender never blocks both passes.",
      "Defender wins it or it goes out: swap with the player who lost it.",
    ],
    points: [
      "Free player: move to the side where the defender isn't.",
      "Open body: receive facing both teammates.",
      "Pass away from the defender's foot, not near it.",
    ],
    progressions: [
      "One-touch passing.",
      "Shrink to 8 × 8 m.",
      "Count passes: 10 = point.",
    ],
    search: "3v1 rondo triangle passing angles kids",
    diagram: {
      field: { type: "grid", w: 10, h: 10 },
      players: [
        { id: "a1", t: "a", x: 5, y: 0.4 },
        { id: "a2", t: "a", x: 9.6, y: 7 },
        { id: "a3", t: "a", x: 0.4, y: 7 },
        { id: "b1", t: "b", x: 5, y: 5 },
      ],
      ball: "a1",
      note: "3v1. Keep a triangle.",
      frames: [
        { note: "Pass away from the defender.", ball: "a2", move: { b1: [7, 4] } },
        { note: "Free player moves to open the angle.", move: { a1: [9.6, 1.5], a3: [0.4, 9.6] } },
        { note: "Two options again: across or back.", move: { b1: [7.5, 6] } },
        { ball: "a3" },
        { note: "Everyone re-adjusts.", move: { a2: [9.6, 9.6], a1: [4, 0.4], b1: [3, 7.5] } },
        { ball: "a1" },
      ],
    },
  },
];
